ARG SOURCE_IMAGE_VERSION="3.13-slim"
ARG SOURCE_IMAGE_NAME="python"
FROM $SOURCE_IMAGE_NAME:$SOURCE_IMAGE_VERSION
ARG IMAGE_VERSION="1.0"
LABEL version=$IMAGE_VERSION
LABEL image_name="baseos"
LABEL description="Base OS image based on python 3.13 slim, with git & OS package updates"

# Update, install packages and clear cache
RUN apt-get update && apt-get install -y git curl && rm -rf /var/lib/apt/lists/*
